---
- name: Check and remove SGSHome_UEMSLinuxAgent.zip
  hosts: linux
  become: true
  tasks:
    - name: Check if the file exists
      stat:
        path: /home/sgs/SGSHome_UEMSLinuxAgent.zip
      register: file_status

    - name: Remove the file if it exists
      file:
        path: /home/sgs/SGSHome_UEMSLinuxAgent.zip
        state: absent
      when: file_status.stat.exists
